apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: patientapp-dev
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
