apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patientapp-dev
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
images:
  - name: patientapp-backend
    newTag: latest
  - name: patientapp-frontend
    newTag: latest
